baseurl: "https://yoroion.github.io/"
languageCode: "en-us"
title: "鎧恩の部屋"
theme: "hugo-tania"
paginate: 6

# disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 

  # Logo will show before the blog title on site navbar.
  titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "Yoroion's Blog"
  siteDesc: "Nothing but real myself"
  author: "Yoroion"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email: yoroion@qq.com
    facebook:
    github: https://github.com/Yoroion
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram: https://t.me/Yoroion4
    twitter: https://twitter.com/yoroion
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP

menu:
  header:
    - name: Articles
      url: "/articles/"
    - name: Friends
      url: "/friends/"
    - name: About
      url: "/about/"
  footer:
    - name: "Copyright © 2021- 2022 Yoroion"
    - name: RSS 订阅
      url: "index.xml"
  

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]